### ISSUE TITLE
auth error

### ISSUE THREAD

**Issue by michael-fang** [aaronksaunders/AngularFire2-Ionic2-Facebook#1]
Hi,

I am getting the following error in the console log when I try to run it. do you know what might cause it?
I double checked the auth domain in firebase console, the auth domain seems to be ok tho.

www.googleapis.com/identitytoolkit/v3/relyingparty/getProjectConfig?key=2tePzI4U4gtKrZcG20Uxho11SrGjUZc117hnISp7&cb=1467527323785:1 GET https://www.googleapis.com/identitytoolkit/v3/relyingparty/getProjectConfig?key=2tePzI4U4gtKrZcG20Uxho11SrGjUZc117hnISp7&cb=1467527323785 400 ()
iframe.js:318  [  0.150s] 

[firebase-auth] Info: The current domain is not authorized for OAuth operations. This will prevent signInWithPopup, signInWithRedirect, linkWithPopup and linkWithRedirect from working. Add your domain to the OAuth redirect domains list in the Firebase console -> Auth section -> Sign in method tab.

**Comment by aaronksaunders** [comment]
you are not running the code I provided because there is not call to any of the methods mentioned above. Please clone the project and start there...

**Comment by michael-fang** [comment]
Hi Sir,

I am running your code, please see the screenshot below. this error seems to occur whenever the angularfire is called(declare in the constructor).

![screen shot 2016-07-03 at 2 46 00 am](https://cloud.githubusercontent.com/assets/16201032/16544155/6678aa94-40c8-11e6-8d7e-bbb2b09fd1fc.png)

**Comment by aaronksaunders** [comment]
Did you do the following...
1. run npm install... 
2. run ionic state restore
3. create your own app in Firebase Application and substitute your own keys?
4. setup up your own facebook APP
5. create the user you are trying to login with

I know this code works because i just submitted and another individual is using it, please ensure you went through the proper steps
